// Auto generated file, please do not modify 


/// ISO 3166-1 alpha-2 code
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[cfg_attr(feature="serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[repr(u8)]
pub enum CCA2 {
	AF,
	AX,
	AL,
	DZ,
	AS,
	AD,
	AO,
	AI,
	AQ,
	AG,
	AR,
	AM,
	AW,
	AU,
	AT,
	AZ,
	BS,
	BH,
	BD,
	BB,
	BY,
	BE,
	BZ,
	BJ,
	BM,
	BT,
	BO,
	BA,
	BW,
	BV,
	BR,
	IO,
	VG,
	BN,
	BG,
	BF,
	BI,
	KH,
	CM,
	CA,
	CV,
	BQ,
	KY,
	CF,
	TD,
	CL,
	CN,
	CX,
	CC,
	CO,
	KM,
	CK,
	CR,
	CI,
	HR,
	CU,
	CW,
	CY,
	CZ,
	DK,
	DJ,
	DM,
	DO,
	CD,
	EC,
	EG,
	SV,
	GQ,
	ER,
	EE,
	SZ,
	ET,
	FK,
	FO,
	FJ,
	FI,
	FR,
	GF,
	PF,
	TF,
	GA,
	GM,
	GE,
	DE,
	GH,
	GI,
	GR,
	GL,
	GD,
	GP,
	GU,
	GT,
	GG,
	GN,
	GW,
	GY,
	HT,
	HM,
	HN,
	HK,
	HU,
	IS,
	IN,
	ID,
	IR,
	IQ,
	IE,
	IM,
	IL,
	IT,
	JM,
	JP,
	JE,
	JO,
	KZ,
	KE,
	KI,
	XK,
	KW,
	KG,
	LA,
	LV,
	LB,
	LS,
	LR,
	LY,
	LI,
	LT,
	LU,
	MO,
	MG,
	MW,
	MY,
	MV,
	ML,
	MT,
	MH,
	MQ,
	MR,
	MU,
	YT,
	MX,
	FM,
	MD,
	MC,
	MN,
	ME,
	MS,
	MA,
	MZ,
	MM,
	NA,
	NR,
	NP,
	NL,
	NC,
	NZ,
	NI,
	NE,
	NG,
	NU,
	NF,
	KP,
	MK,
	MP,
	NO,
	OM,
	PK,
	PW,
	PS,
	PA,
	PG,
	PY,
	PE,
	PH,
	PN,
	PL,
	PT,
	PR,
	QA,
	CG,
	RE,
	RO,
	RU,
	RW,
	BL,
	SH,
	KN,
	LC,
	MF,
	PM,
	VC,
	WS,
	SM,
	ST,
	SA,
	SN,
	RS,
	SC,
	SL,
	SG,
	SX,
	SK,
	SI,
	SB,
	SO,
	ZA,
	GS,
	KR,
	SS,
	ES,
	LK,
	SD,
	SR,
	SJ,
	SE,
	CH,
	SY,
	TW,
	TJ,
	TZ,
	TH,
	TL,
	TG,
	TK,
	TO,
	TT,
	TN,
	TR,
	TM,
	TC,
	TV,
	UG,
	UA,
	AE,
	GB,
	US,
	UM,
	VI,
	UY,
	UZ,
	VU,
	VA,
	VE,
	VN,
	WF,
	EH,
	YE,
	ZM,
	ZW,
}

/// ISO 3166-1 alpha-3 code
#[derive(Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
#[cfg_attr(feature="serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[repr(u8)]
pub enum CCA3 {
	AFG,
	ALA,
	ALB,
	DZA,
	ASM,
	AND,
	AGO,
	AIA,
	ATA,
	ATG,
	ARG,
	ARM,
	ABW,
	AUS,
	AUT,
	AZE,
	BHS,
	BHR,
	BGD,
	BRB,
	BLR,
	BEL,
	BLZ,
	BEN,
	BMU,
	BTN,
	BOL,
	BIH,
	BWA,
	BVT,
	BRA,
	IOT,
	VGB,
	BRN,
	BGR,
	BFA,
	BDI,
	KHM,
	CMR,
	CAN,
	CPV,
	BES,
	CYM,
	CAF,
	TCD,
	CHL,
	CHN,
	CXR,
	CCK,
	COL,
	COM,
	COK,
	CRI,
	CIV,
	HRV,
	CUB,
	CUW,
	CYP,
	CZE,
	DNK,
	DJI,
	DMA,
	DOM,
	COD,
	ECU,
	EGY,
	SLV,
	GNQ,
	ERI,
	EST,
	SWZ,
	ETH,
	FLK,
	FRO,
	FJI,
	FIN,
	FRA,
	GUF,
	PYF,
	ATF,
	GAB,
	GMB,
	GEO,
	DEU,
	GHA,
	GIB,
	GRC,
	GRL,
	GRD,
	GLP,
	GUM,
	GTM,
	GGY,
	GIN,
	GNB,
	GUY,
	HTI,
	HMD,
	HND,
	HKG,
	HUN,
	ISL,
	IND,
	IDN,
	IRN,
	IRQ,
	IRL,
	IMN,
	ISR,
	ITA,
	JAM,
	JPN,
	JEY,
	JOR,
	KAZ,
	KEN,
	KIR,
	UNK,
	KWT,
	KGZ,
	LAO,
	LVA,
	LBN,
	LSO,
	LBR,
	LBY,
	LIE,
	LTU,
	LUX,
	MAC,
	MDG,
	MWI,
	MYS,
	MDV,
	MLI,
	MLT,
	MHL,
	MTQ,
	MRT,
	MUS,
	MYT,
	MEX,
	FSM,
	MDA,
	MCO,
	MNG,
	MNE,
	MSR,
	MAR,
	MOZ,
	MMR,
	NAM,
	NRU,
	NPL,
	NLD,
	NCL,
	NZL,
	NIC,
	NER,
	NGA,
	NIU,
	NFK,
	PRK,
	MKD,
	MNP,
	NOR,
	OMN,
	PAK,
	PLW,
	PSE,
	PAN,
	PNG,
	PRY,
	PER,
	PHL,
	PCN,
	POL,
	PRT,
	PRI,
	QAT,
	COG,
	REU,
	ROU,
	RUS,
	RWA,
	BLM,
	SHN,
	KNA,
	LCA,
	MAF,
	SPM,
	VCT,
	WSM,
	SMR,
	STP,
	SAU,
	SEN,
	SRB,
	SYC,
	SLE,
	SGP,
	SXM,
	SVK,
	SVN,
	SLB,
	SOM,
	ZAF,
	SGS,
	KOR,
	SSD,
	ESP,
	LKA,
	SDN,
	SUR,
	SJM,
	SWE,
	CHE,
	SYR,
	TWN,
	TJK,
	TZA,
	THA,
	TLS,
	TGO,
	TKL,
	TON,
	TTO,
	TUN,
	TUR,
	TKM,
	TCA,
	TUV,
	UGA,
	UKR,
	ARE,
	GBR,
	USA,
	UMI,
	VIR,
	URY,
	UZB,
	VUT,
	VAT,
	VEN,
	VNM,
	WLF,
	ESH,
	YEM,
	ZMB,
	ZWE,
}

impl core::ops::Deref for CCA2 {
    type Target = super::types::Country;

    fn deref(&self) -> &Self::Target {
        match self {
            CCA2::AF => super::consts::AF,
            CCA2::AX => super::consts::AX,
            CCA2::AL => super::consts::AL,
            CCA2::DZ => super::consts::DZ,
            CCA2::AS => super::consts::AS,
            CCA2::AD => super::consts::AD,
            CCA2::AO => super::consts::AO,
            CCA2::AI => super::consts::AI,
            CCA2::AQ => super::consts::AQ,
            CCA2::AG => super::consts::AG,
            CCA2::AR => super::consts::AR,
            CCA2::AM => super::consts::AM,
            CCA2::AW => super::consts::AW,
            CCA2::AU => super::consts::AU,
            CCA2::AT => super::consts::AT,
            CCA2::AZ => super::consts::AZ,
            CCA2::BS => super::consts::BS,
            CCA2::BH => super::consts::BH,
            CCA2::BD => super::consts::BD,
            CCA2::BB => super::consts::BB,
            CCA2::BY => super::consts::BY,
            CCA2::BE => super::consts::BE,
            CCA2::BZ => super::consts::BZ,
            CCA2::BJ => super::consts::BJ,
            CCA2::BM => super::consts::BM,
            CCA2::BT => super::consts::BT,
            CCA2::BO => super::consts::BO,
            CCA2::BA => super::consts::BA,
            CCA2::BW => super::consts::BW,
            CCA2::BV => super::consts::BV,
            CCA2::BR => super::consts::BR,
            CCA2::IO => super::consts::IO,
            CCA2::VG => super::consts::VG,
            CCA2::BN => super::consts::BN,
            CCA2::BG => super::consts::BG,
            CCA2::BF => super::consts::BF,
            CCA2::BI => super::consts::BI,
            CCA2::KH => super::consts::KH,
            CCA2::CM => super::consts::CM,
            CCA2::CA => super::consts::CA,
            CCA2::CV => super::consts::CV,
            CCA2::BQ => super::consts::BQ,
            CCA2::KY => super::consts::KY,
            CCA2::CF => super::consts::CF,
            CCA2::TD => super::consts::TD,
            CCA2::CL => super::consts::CL,
            CCA2::CN => super::consts::CN,
            CCA2::CX => super::consts::CX,
            CCA2::CC => super::consts::CC,
            CCA2::CO => super::consts::CO,
            CCA2::KM => super::consts::KM,
            CCA2::CK => super::consts::CK,
            CCA2::CR => super::consts::CR,
            CCA2::CI => super::consts::CI,
            CCA2::HR => super::consts::HR,
            CCA2::CU => super::consts::CU,
            CCA2::CW => super::consts::CW,
            CCA2::CY => super::consts::CY,
            CCA2::CZ => super::consts::CZ,
            CCA2::DK => super::consts::DK,
            CCA2::DJ => super::consts::DJ,
            CCA2::DM => super::consts::DM,
            CCA2::DO => super::consts::DO,
            CCA2::CD => super::consts::CD,
            CCA2::EC => super::consts::EC,
            CCA2::EG => super::consts::EG,
            CCA2::SV => super::consts::SV,
            CCA2::GQ => super::consts::GQ,
            CCA2::ER => super::consts::ER,
            CCA2::EE => super::consts::EE,
            CCA2::SZ => super::consts::SZ,
            CCA2::ET => super::consts::ET,
            CCA2::FK => super::consts::FK,
            CCA2::FO => super::consts::FO,
            CCA2::FJ => super::consts::FJ,
            CCA2::FI => super::consts::FI,
            CCA2::FR => super::consts::FR,
            CCA2::GF => super::consts::GF,
            CCA2::PF => super::consts::PF,
            CCA2::TF => super::consts::TF,
            CCA2::GA => super::consts::GA,
            CCA2::GM => super::consts::GM,
            CCA2::GE => super::consts::GE,
            CCA2::DE => super::consts::DE,
            CCA2::GH => super::consts::GH,
            CCA2::GI => super::consts::GI,
            CCA2::GR => super::consts::GR,
            CCA2::GL => super::consts::GL,
            CCA2::GD => super::consts::GD,
            CCA2::GP => super::consts::GP,
            CCA2::GU => super::consts::GU,
            CCA2::GT => super::consts::GT,
            CCA2::GG => super::consts::GG,
            CCA2::GN => super::consts::GN,
            CCA2::GW => super::consts::GW,
            CCA2::GY => super::consts::GY,
            CCA2::HT => super::consts::HT,
            CCA2::HM => super::consts::HM,
            CCA2::HN => super::consts::HN,
            CCA2::HK => super::consts::HK,
            CCA2::HU => super::consts::HU,
            CCA2::IS => super::consts::IS,
            CCA2::IN => super::consts::IN,
            CCA2::ID => super::consts::ID,
            CCA2::IR => super::consts::IR,
            CCA2::IQ => super::consts::IQ,
            CCA2::IE => super::consts::IE,
            CCA2::IM => super::consts::IM,
            CCA2::IL => super::consts::IL,
            CCA2::IT => super::consts::IT,
            CCA2::JM => super::consts::JM,
            CCA2::JP => super::consts::JP,
            CCA2::JE => super::consts::JE,
            CCA2::JO => super::consts::JO,
            CCA2::KZ => super::consts::KZ,
            CCA2::KE => super::consts::KE,
            CCA2::KI => super::consts::KI,
            CCA2::XK => super::consts::XK,
            CCA2::KW => super::consts::KW,
            CCA2::KG => super::consts::KG,
            CCA2::LA => super::consts::LA,
            CCA2::LV => super::consts::LV,
            CCA2::LB => super::consts::LB,
            CCA2::LS => super::consts::LS,
            CCA2::LR => super::consts::LR,
            CCA2::LY => super::consts::LY,
            CCA2::LI => super::consts::LI,
            CCA2::LT => super::consts::LT,
            CCA2::LU => super::consts::LU,
            CCA2::MO => super::consts::MO,
            CCA2::MG => super::consts::MG,
            CCA2::MW => super::consts::MW,
            CCA2::MY => super::consts::MY,
            CCA2::MV => super::consts::MV,
            CCA2::ML => super::consts::ML,
            CCA2::MT => super::consts::MT,
            CCA2::MH => super::consts::MH,
            CCA2::MQ => super::consts::MQ,
            CCA2::MR => super::consts::MR,
            CCA2::MU => super::consts::MU,
            CCA2::YT => super::consts::YT,
            CCA2::MX => super::consts::MX,
            CCA2::FM => super::consts::FM,
            CCA2::MD => super::consts::MD,
            CCA2::MC => super::consts::MC,
            CCA2::MN => super::consts::MN,
            CCA2::ME => super::consts::ME,
            CCA2::MS => super::consts::MS,
            CCA2::MA => super::consts::MA,
            CCA2::MZ => super::consts::MZ,
            CCA2::MM => super::consts::MM,
            CCA2::NA => super::consts::NA,
            CCA2::NR => super::consts::NR,
            CCA2::NP => super::consts::NP,
            CCA2::NL => super::consts::NL,
            CCA2::NC => super::consts::NC,
            CCA2::NZ => super::consts::NZ,
            CCA2::NI => super::consts::NI,
            CCA2::NE => super::consts::NE,
            CCA2::NG => super::consts::NG,
            CCA2::NU => super::consts::NU,
            CCA2::NF => super::consts::NF,
            CCA2::KP => super::consts::KP,
            CCA2::MK => super::consts::MK,
            CCA2::MP => super::consts::MP,
            CCA2::NO => super::consts::NO,
            CCA2::OM => super::consts::OM,
            CCA2::PK => super::consts::PK,
            CCA2::PW => super::consts::PW,
            CCA2::PS => super::consts::PS,
            CCA2::PA => super::consts::PA,
            CCA2::PG => super::consts::PG,
            CCA2::PY => super::consts::PY,
            CCA2::PE => super::consts::PE,
            CCA2::PH => super::consts::PH,
            CCA2::PN => super::consts::PN,
            CCA2::PL => super::consts::PL,
            CCA2::PT => super::consts::PT,
            CCA2::PR => super::consts::PR,
            CCA2::QA => super::consts::QA,
            CCA2::CG => super::consts::CG,
            CCA2::RE => super::consts::RE,
            CCA2::RO => super::consts::RO,
            CCA2::RU => super::consts::RU,
            CCA2::RW => super::consts::RW,
            CCA2::BL => super::consts::BL,
            CCA2::SH => super::consts::SH,
            CCA2::KN => super::consts::KN,
            CCA2::LC => super::consts::LC,
            CCA2::MF => super::consts::MF,
            CCA2::PM => super::consts::PM,
            CCA2::VC => super::consts::VC,
            CCA2::WS => super::consts::WS,
            CCA2::SM => super::consts::SM,
            CCA2::ST => super::consts::ST,
            CCA2::SA => super::consts::SA,
            CCA2::SN => super::consts::SN,
            CCA2::RS => super::consts::RS,
            CCA2::SC => super::consts::SC,
            CCA2::SL => super::consts::SL,
            CCA2::SG => super::consts::SG,
            CCA2::SX => super::consts::SX,
            CCA2::SK => super::consts::SK,
            CCA2::SI => super::consts::SI,
            CCA2::SB => super::consts::SB,
            CCA2::SO => super::consts::SO,
            CCA2::ZA => super::consts::ZA,
            CCA2::GS => super::consts::GS,
            CCA2::KR => super::consts::KR,
            CCA2::SS => super::consts::SS,
            CCA2::ES => super::consts::ES,
            CCA2::LK => super::consts::LK,
            CCA2::SD => super::consts::SD,
            CCA2::SR => super::consts::SR,
            CCA2::SJ => super::consts::SJ,
            CCA2::SE => super::consts::SE,
            CCA2::CH => super::consts::CH,
            CCA2::SY => super::consts::SY,
            CCA2::TW => super::consts::TW,
            CCA2::TJ => super::consts::TJ,
            CCA2::TZ => super::consts::TZ,
            CCA2::TH => super::consts::TH,
            CCA2::TL => super::consts::TL,
            CCA2::TG => super::consts::TG,
            CCA2::TK => super::consts::TK,
            CCA2::TO => super::consts::TO,
            CCA2::TT => super::consts::TT,
            CCA2::TN => super::consts::TN,
            CCA2::TR => super::consts::TR,
            CCA2::TM => super::consts::TM,
            CCA2::TC => super::consts::TC,
            CCA2::TV => super::consts::TV,
            CCA2::UG => super::consts::UG,
            CCA2::UA => super::consts::UA,
            CCA2::AE => super::consts::AE,
            CCA2::GB => super::consts::GB,
            CCA2::US => super::consts::US,
            CCA2::UM => super::consts::UM,
            CCA2::VI => super::consts::VI,
            CCA2::UY => super::consts::UY,
            CCA2::UZ => super::consts::UZ,
            CCA2::VU => super::consts::VU,
            CCA2::VA => super::consts::VA,
            CCA2::VE => super::consts::VE,
            CCA2::VN => super::consts::VN,
            CCA2::WF => super::consts::WF,
            CCA2::EH => super::consts::EH,
            CCA2::YE => super::consts::YE,
            CCA2::ZM => super::consts::ZM,
            CCA2::ZW => super::consts::ZW,
            
        }
    }
}
impl core::ops::Deref for CCA3 {
    type Target = super::types::Country;

    fn deref(&self) -> &Self::Target {
        match self {
            CCA3::AFG => super::consts::AFG,
            CCA3::ALA => super::consts::ALA,
            CCA3::ALB => super::consts::ALB,
            CCA3::DZA => super::consts::DZA,
            CCA3::ASM => super::consts::ASM,
            CCA3::AND => super::consts::AND,
            CCA3::AGO => super::consts::AGO,
            CCA3::AIA => super::consts::AIA,
            CCA3::ATA => super::consts::ATA,
            CCA3::ATG => super::consts::ATG,
            CCA3::ARG => super::consts::ARG,
            CCA3::ARM => super::consts::ARM,
            CCA3::ABW => super::consts::ABW,
            CCA3::AUS => super::consts::AUS,
            CCA3::AUT => super::consts::AUT,
            CCA3::AZE => super::consts::AZE,
            CCA3::BHS => super::consts::BHS,
            CCA3::BHR => super::consts::BHR,
            CCA3::BGD => super::consts::BGD,
            CCA3::BRB => super::consts::BRB,
            CCA3::BLR => super::consts::BLR,
            CCA3::BEL => super::consts::BEL,
            CCA3::BLZ => super::consts::BLZ,
            CCA3::BEN => super::consts::BEN,
            CCA3::BMU => super::consts::BMU,
            CCA3::BTN => super::consts::BTN,
            CCA3::BOL => super::consts::BOL,
            CCA3::BIH => super::consts::BIH,
            CCA3::BWA => super::consts::BWA,
            CCA3::BVT => super::consts::BVT,
            CCA3::BRA => super::consts::BRA,
            CCA3::IOT => super::consts::IOT,
            CCA3::VGB => super::consts::VGB,
            CCA3::BRN => super::consts::BRN,
            CCA3::BGR => super::consts::BGR,
            CCA3::BFA => super::consts::BFA,
            CCA3::BDI => super::consts::BDI,
            CCA3::KHM => super::consts::KHM,
            CCA3::CMR => super::consts::CMR,
            CCA3::CAN => super::consts::CAN,
            CCA3::CPV => super::consts::CPV,
            CCA3::BES => super::consts::BES,
            CCA3::CYM => super::consts::CYM,
            CCA3::CAF => super::consts::CAF,
            CCA3::TCD => super::consts::TCD,
            CCA3::CHL => super::consts::CHL,
            CCA3::CHN => super::consts::CHN,
            CCA3::CXR => super::consts::CXR,
            CCA3::CCK => super::consts::CCK,
            CCA3::COL => super::consts::COL,
            CCA3::COM => super::consts::COM,
            CCA3::COK => super::consts::COK,
            CCA3::CRI => super::consts::CRI,
            CCA3::CIV => super::consts::CIV,
            CCA3::HRV => super::consts::HRV,
            CCA3::CUB => super::consts::CUB,
            CCA3::CUW => super::consts::CUW,
            CCA3::CYP => super::consts::CYP,
            CCA3::CZE => super::consts::CZE,
            CCA3::DNK => super::consts::DNK,
            CCA3::DJI => super::consts::DJI,
            CCA3::DMA => super::consts::DMA,
            CCA3::DOM => super::consts::DOM,
            CCA3::COD => super::consts::COD,
            CCA3::ECU => super::consts::ECU,
            CCA3::EGY => super::consts::EGY,
            CCA3::SLV => super::consts::SLV,
            CCA3::GNQ => super::consts::GNQ,
            CCA3::ERI => super::consts::ERI,
            CCA3::EST => super::consts::EST,
            CCA3::SWZ => super::consts::SWZ,
            CCA3::ETH => super::consts::ETH,
            CCA3::FLK => super::consts::FLK,
            CCA3::FRO => super::consts::FRO,
            CCA3::FJI => super::consts::FJI,
            CCA3::FIN => super::consts::FIN,
            CCA3::FRA => super::consts::FRA,
            CCA3::GUF => super::consts::GUF,
            CCA3::PYF => super::consts::PYF,
            CCA3::ATF => super::consts::ATF,
            CCA3::GAB => super::consts::GAB,
            CCA3::GMB => super::consts::GMB,
            CCA3::GEO => super::consts::GEO,
            CCA3::DEU => super::consts::DEU,
            CCA3::GHA => super::consts::GHA,
            CCA3::GIB => super::consts::GIB,
            CCA3::GRC => super::consts::GRC,
            CCA3::GRL => super::consts::GRL,
            CCA3::GRD => super::consts::GRD,
            CCA3::GLP => super::consts::GLP,
            CCA3::GUM => super::consts::GUM,
            CCA3::GTM => super::consts::GTM,
            CCA3::GGY => super::consts::GGY,
            CCA3::GIN => super::consts::GIN,
            CCA3::GNB => super::consts::GNB,
            CCA3::GUY => super::consts::GUY,
            CCA3::HTI => super::consts::HTI,
            CCA3::HMD => super::consts::HMD,
            CCA3::HND => super::consts::HND,
            CCA3::HKG => super::consts::HKG,
            CCA3::HUN => super::consts::HUN,
            CCA3::ISL => super::consts::ISL,
            CCA3::IND => super::consts::IND,
            CCA3::IDN => super::consts::IDN,
            CCA3::IRN => super::consts::IRN,
            CCA3::IRQ => super::consts::IRQ,
            CCA3::IRL => super::consts::IRL,
            CCA3::IMN => super::consts::IMN,
            CCA3::ISR => super::consts::ISR,
            CCA3::ITA => super::consts::ITA,
            CCA3::JAM => super::consts::JAM,
            CCA3::JPN => super::consts::JPN,
            CCA3::JEY => super::consts::JEY,
            CCA3::JOR => super::consts::JOR,
            CCA3::KAZ => super::consts::KAZ,
            CCA3::KEN => super::consts::KEN,
            CCA3::KIR => super::consts::KIR,
            CCA3::UNK => super::consts::UNK,
            CCA3::KWT => super::consts::KWT,
            CCA3::KGZ => super::consts::KGZ,
            CCA3::LAO => super::consts::LAO,
            CCA3::LVA => super::consts::LVA,
            CCA3::LBN => super::consts::LBN,
            CCA3::LSO => super::consts::LSO,
            CCA3::LBR => super::consts::LBR,
            CCA3::LBY => super::consts::LBY,
            CCA3::LIE => super::consts::LIE,
            CCA3::LTU => super::consts::LTU,
            CCA3::LUX => super::consts::LUX,
            CCA3::MAC => super::consts::MAC,
            CCA3::MDG => super::consts::MDG,
            CCA3::MWI => super::consts::MWI,
            CCA3::MYS => super::consts::MYS,
            CCA3::MDV => super::consts::MDV,
            CCA3::MLI => super::consts::MLI,
            CCA3::MLT => super::consts::MLT,
            CCA3::MHL => super::consts::MHL,
            CCA3::MTQ => super::consts::MTQ,
            CCA3::MRT => super::consts::MRT,
            CCA3::MUS => super::consts::MUS,
            CCA3::MYT => super::consts::MYT,
            CCA3::MEX => super::consts::MEX,
            CCA3::FSM => super::consts::FSM,
            CCA3::MDA => super::consts::MDA,
            CCA3::MCO => super::consts::MCO,
            CCA3::MNG => super::consts::MNG,
            CCA3::MNE => super::consts::MNE,
            CCA3::MSR => super::consts::MSR,
            CCA3::MAR => super::consts::MAR,
            CCA3::MOZ => super::consts::MOZ,
            CCA3::MMR => super::consts::MMR,
            CCA3::NAM => super::consts::NAM,
            CCA3::NRU => super::consts::NRU,
            CCA3::NPL => super::consts::NPL,
            CCA3::NLD => super::consts::NLD,
            CCA3::NCL => super::consts::NCL,
            CCA3::NZL => super::consts::NZL,
            CCA3::NIC => super::consts::NIC,
            CCA3::NER => super::consts::NER,
            CCA3::NGA => super::consts::NGA,
            CCA3::NIU => super::consts::NIU,
            CCA3::NFK => super::consts::NFK,
            CCA3::PRK => super::consts::PRK,
            CCA3::MKD => super::consts::MKD,
            CCA3::MNP => super::consts::MNP,
            CCA3::NOR => super::consts::NOR,
            CCA3::OMN => super::consts::OMN,
            CCA3::PAK => super::consts::PAK,
            CCA3::PLW => super::consts::PLW,
            CCA3::PSE => super::consts::PSE,
            CCA3::PAN => super::consts::PAN,
            CCA3::PNG => super::consts::PNG,
            CCA3::PRY => super::consts::PRY,
            CCA3::PER => super::consts::PER,
            CCA3::PHL => super::consts::PHL,
            CCA3::PCN => super::consts::PCN,
            CCA3::POL => super::consts::POL,
            CCA3::PRT => super::consts::PRT,
            CCA3::PRI => super::consts::PRI,
            CCA3::QAT => super::consts::QAT,
            CCA3::COG => super::consts::COG,
            CCA3::REU => super::consts::REU,
            CCA3::ROU => super::consts::ROU,
            CCA3::RUS => super::consts::RUS,
            CCA3::RWA => super::consts::RWA,
            CCA3::BLM => super::consts::BLM,
            CCA3::SHN => super::consts::SHN,
            CCA3::KNA => super::consts::KNA,
            CCA3::LCA => super::consts::LCA,
            CCA3::MAF => super::consts::MAF,
            CCA3::SPM => super::consts::SPM,
            CCA3::VCT => super::consts::VCT,
            CCA3::WSM => super::consts::WSM,
            CCA3::SMR => super::consts::SMR,
            CCA3::STP => super::consts::STP,
            CCA3::SAU => super::consts::SAU,
            CCA3::SEN => super::consts::SEN,
            CCA3::SRB => super::consts::SRB,
            CCA3::SYC => super::consts::SYC,
            CCA3::SLE => super::consts::SLE,
            CCA3::SGP => super::consts::SGP,
            CCA3::SXM => super::consts::SXM,
            CCA3::SVK => super::consts::SVK,
            CCA3::SVN => super::consts::SVN,
            CCA3::SLB => super::consts::SLB,
            CCA3::SOM => super::consts::SOM,
            CCA3::ZAF => super::consts::ZAF,
            CCA3::SGS => super::consts::SGS,
            CCA3::KOR => super::consts::KOR,
            CCA3::SSD => super::consts::SSD,
            CCA3::ESP => super::consts::ESP,
            CCA3::LKA => super::consts::LKA,
            CCA3::SDN => super::consts::SDN,
            CCA3::SUR => super::consts::SUR,
            CCA3::SJM => super::consts::SJM,
            CCA3::SWE => super::consts::SWE,
            CCA3::CHE => super::consts::CHE,
            CCA3::SYR => super::consts::SYR,
            CCA3::TWN => super::consts::TWN,
            CCA3::TJK => super::consts::TJK,
            CCA3::TZA => super::consts::TZA,
            CCA3::THA => super::consts::THA,
            CCA3::TLS => super::consts::TLS,
            CCA3::TGO => super::consts::TGO,
            CCA3::TKL => super::consts::TKL,
            CCA3::TON => super::consts::TON,
            CCA3::TTO => super::consts::TTO,
            CCA3::TUN => super::consts::TUN,
            CCA3::TUR => super::consts::TUR,
            CCA3::TKM => super::consts::TKM,
            CCA3::TCA => super::consts::TCA,
            CCA3::TUV => super::consts::TUV,
            CCA3::UGA => super::consts::UGA,
            CCA3::UKR => super::consts::UKR,
            CCA3::ARE => super::consts::ARE,
            CCA3::GBR => super::consts::GBR,
            CCA3::USA => super::consts::USA,
            CCA3::UMI => super::consts::UMI,
            CCA3::VIR => super::consts::VIR,
            CCA3::URY => super::consts::URY,
            CCA3::UZB => super::consts::UZB,
            CCA3::VUT => super::consts::VUT,
            CCA3::VAT => super::consts::VAT,
            CCA3::VEN => super::consts::VEN,
            CCA3::VNM => super::consts::VNM,
            CCA3::WLF => super::consts::WLF,
            CCA3::ESH => super::consts::ESH,
            CCA3::YEM => super::consts::YEM,
            CCA3::ZMB => super::consts::ZMB,
            CCA3::ZWE => super::consts::ZWE,
            
        }
    }
}

